:_content-type: CONCEPT
:imagesdir: ../../images

[id="exploring-values"]
= Exploring values

A value represents a specific configuration or parameter that influences the behavior of a validated pattern. These values may range from simple settings like port numbers to more complex elements such as host names and DNS entries. Their role is to ensure that validated patterns adapt to diverse needs and scenarios, whether they involve straightforward settings or more complex configurations. Values are instrumental in ensuring the efficient and seamless operation of validated patterns.

[id="benefits-of-using-values-files"]
== Benefits of using values files

Values files offer a flexible and modular approach to deploying validated patterns, providing key advantages:

* *Adaptability*: Empowers adjustment of validated patterns or applications to diverse deployment scenarios without direct modifications to the underlying codebase.
* *Maintainability*: Streamlines the process of updating and managing configurations, promoting maintainability and reducing the likelihood of errors during deployment.


[id="integration-of-values-files"]
== Integration of values files in validated patterns

Validated patterns use values files to dynamically adapt to different deployment scenarios. During deployment, the pattern references the values file to fetch specific configurations, making the deployment process versatile and adaptable.

*Example of a value in a values file*


[source,yaml]
----
applications:
  coffeeshop-test:
    name: quarkuscoffeeshop-demo
    namespace: quarkuscoffeeshop-demo
    project: quarkuscoffeeshop-demo
    path: charts/store/quarkuscoffeeshop-charts
    overrides:
      - name: projectnamespace
        value: quarkuscoffeeshop-demo
      - name: Release.release-namespace
        value: quarkuscoffeeshop-demo
      - name: storeid
        value: TEST
----

In this example, the `coffeeshop-test` application has specific overrides, such as setting the `projectnamespace` to `quarkuscoffeeshop-demo`, the `Release.release-namespace` to `quarkuscoffeeshop-demo`, and the `storeid` to `TEST`. These values can be easily adjusted based on the desired configuration for the application, showcasing the flexibility provided by values files in tailoring deployments to specific requirements.
