:_content-type: CONCEPT
:imagesdir: ../../images

[id="managing-lifecycle-kubernetes-applications"]
= Managing the lifecycle of Kubernetes applications

Two options are available to you that allow you to manage the lifecycle of Kubernetes applications you want to deploy with the validated patterns framework. The tools supported are `Kustomize` and `Helm`. 

* *Kustomize*: Kustomize is a configuration management tool to make declarative changes to application configurations and components and preserve the original base YAML files. Kustomize allows you to manage Kubernetes resource files in a declarative manner, using a set of layered configurations. This makes it easier to maintain, version, and apply changes to Kubernetes resources without having to modify the original YAML files directly.
* *Helm*: Helm is a package manager for Kubernetes, which simplifies the process of defining, installing, and upgrading complex Kubernetes applications. It manages Kubernetes manifests using a packaging format called `Charts`.

Helm is the preferred mechanism for deploying applications in the validated patterns framework, and detailed information about its usage follows.