:_content-type: CONCEPT
:imagesdir: ../../images

[id="contributing-to-docs-contributing"]
= Contribute to Validated Patterns documentation

== Different ways to contribute

There are a few different ways you can contribute to Validated Patterns documentation:

* Email the Validated Patterns team at mailto:hybrid-cloud-patterns@googlegroups.com[hybrid-cloud-patterns@googlegroups.com].
* Create a link:https://github.com/validatedpatterns/docs/issues[GitHub] or link:https://issues.redhat.com/projects/MBP/issues[Jira issue] .
//to-do: Add link to the contribution workflow when we have a proper one. You might need to create a new file
* Submit a pull request (PR). To create a PR, create a local clone of your own fork of the link:https://github.com/validatedpatterns/docs[Validated Patterns docs repository], make your changes, and submit a PR. This option is best if you have substantial changes.
//to-do:For more details on creating a PR see <topic_link_to_contribution_workflow>.

== Contribution workflow

When you submit a PR, the https://github.com/orgs/hybrid-cloud-patterns/teams/docs[Validated Patterns Docs team] reviews the PR and arranges further reviews by Quality Engineering (QE), subject matter experts (SMEs), and others, as required. If the PR requires changes, updates, or corrections, the reviewers add comments in the PR. The documentation team merges the PR after you have implemented all feedback, and you have squashed all commits.


== Repository organization

//to-do:Placeholder to explain how assemblies, modules, images, common/attribute folders are organized.
----
├── archetypes
├── content
│   └── blog
|   └── contribute
|   └── learn
|   └── patterns
|       └── multicloud-gitops
|       |   └──_index.adoc
|       |   └──mcg-getting-started.adoc
|       |
|       └── medical-diagnosis
|           └──_index.adoc
|           └── medical-diagnosis-assembly.adoc
├── layouts
│   └── _default
|   └── blog
├── modules
│   └── multicloud-gitops-logical-architecture.adoc
│   └── multicloud-gitops-physical-architecture.adoc
├── static
|   └── images
├── themes/patternfly
├── config.yaml
└── README.adoc
----

//to-do: commenting out this section since presently this is rendered as one single page and the topics under the link immediately follow the "Next steps" section. Originally, the links under the "Next steps" section were meant to open as new pages, which they currently don't.
//== Next steps
//* link:https://validatedpatterns.io/contribute/contribute-to-docs/#contributing-to-docs-tools-and-setup[Install and set up the tools and software] on your workstation so that you can contribute.
//* link:https://validatedpatterns.io/contribute/contribute-to-docs/#contributing-to-docs-doc-guidelines[Review the documentation guidelines] to understand some basic guidelines to keep documentation consistent across our content.