[id="contributing-to-docs-contributing"]
= Contribute to Hybrid Cloud Patterns documentation
:icons:
:description: Contribute to Hybrid Cloud Patterns documentation
:imagesdir: ../images


== Different ways to contribute

There are a few different ways you can contribute to Hybrid Cloud Patterns documentation:

* Email the Hybrid Cloud Patterns team at `hybrid-cloud-patterns@googlegroups.com`.
* Create a link:https://github.com/hybrid-cloud-patterns/docs/issues[GitHub] or link:https://issues.redhat.com/projects/MBP/issues[Jira issue] .
//to-do: Add link to the contribution workflow when we have a proper one. You might need to create a new file
* Submit a pull request (PR). To create a PR, create a local clone of your own fork of the link:https://github.com/hybrid-cloud-patterns/docs[Hybrid Cloud Patterns docs repository], make your changes, and submit a PR. This option is best if you have substantial changes.
//to-do:For more details on creating a PR see <topic_link_to_contribution_workflow>.

== Contribution workflow

When you submit a PR, the https://github.com/orgs/hybrid-cloud-patterns/teams/docs[Hybrid Cloud Patterns Docs team] reviews the PR and arranges further reviews by Quality Engineering (QE), subject matter experts (SMEs), and others, as required. If the PR requires changes, updates, or corrections, the reviewers add comments in the PR. The documentation team merges the PR after you have implemented all feedback, and you have squashed all commits.


== Repository organization

//to-do:Placeholder to explain how assemblies, modules, images, common/attribute folders are organized.
----
├── archetypes
├── content
│   └── blog
|   └── contribute
|   └── learn
|   |  └── multicloud-gitops
|   |  | └──multicloud-gitops-assembly.adoc
|   |  └── medical-diagnosis
|   |    └── medical-diagnosis-assembly.adoc
|   └── patterns
├── layouts
│   └── _default
|   └── blog
├── modules
│   └── multicloud-gitops-logical-architecture.adoc
│   └── multicloud-gitops-physical-architecture.adoc
├── static
├── themes/patternfly
├── config.yaml
└── README.adoc
----

== Next steps
* link:https://hybrid-cloud-patterns.io/contribute/contribute-to-docs/#contributing-to-docs-tools-and-setup[Install and set up the tools and software] on your workstation so that you can contribute.
* link:https://hybrid-cloud-patterns.io/contribute/contribute-to-docs/#contributing-to-docs-doc-guidelines[Review the documentation guidelines] to
understand some basic guidelines to keep documentation consistent
across our content.
