:_content-type: CONCEPT
:imagesdir: ../../images

[id="contributing-to-docs-doc-guidelines"]
= Documentation guidelines
Documentation guidelines for contributing to the Validated Patterns Docs

== General guidelines

When authoring content, follow these style guides:

* link:https://redhat-documentation.github.io/supplementary-style-guide/[Red Hat Supplementary Style Guide]
* link:https://www.ibm.com/docs/en/ibm-style[IBM Style], especially link:https://www.ibm.com/docs/en/ibm-style?topic=word-usage[word usage]
+
NOTE: When asked for an IBMid, Red Hat associates can use their Red Hat e-mail.
* link:https://redhat-documentation.github.io/modular-docs/#writing-mod-docs[Modular documentation reference guide]
* link:https://github.com/redhat-documentation/modular-docs/tree/main/modular-docs-manual/files[Modular documentation templates]

== Modular documentation terms

[options="header"]
|===

|Modular doc entity |Description

|Asssembly
|An _assembly_ is a collection of modules that describes how to accomplish a user story.

|Concept module
|A _concept_ contains information to support the tasks that users want to do and must not include task information like commands or numbered steps. In most cases, create your concepts as individual modules and include them in appropriate assemblies. Avoid using gerunds in concept titles. "About <concept>" is a common concept module title.

|Procedure module
|A procedure contains the steps that users follow to complete a process or task. Procedures contain ordered steps and explicit commands. In most cases, create your procedures as individual modules and include them in appropriate assemblies. Use a gerund in the procedure title, such as "Creating".

|Reference module
|A reference module provides data that users might want to look up, but do not need to remember. A reference module has a very strict structure, often in the form of a list or a table. A well-organized reference module enables users to scan it quickly to find the details they want.

|===


== Naming conventions for assembly and module files
Use lowercase separated by dash. Create assembly and module file names that accurately and closely reflect the title of the assembly or module.

.Examples
* `designing-guided-decision-tables.adoc` (Assembly of guided decision table modules)
* `guided-decision-tables.adoc` (Concept module)
* `creating-guided-decision-tables.adoc` (Procedure module for creating)
* `guided-decision-table-examples.adoc` (Reference module with examples)

=== Content type attributes

Each `.adoc` file must contain a `:_content-type:` attribute in its metadata that indicates its file type. This information is used by some publication processes to sort and label files.

Add the attribute from the following list that corresponds to your file type:

* `:_content-type: ASSEMBLY`
* `:_content-type: CONCEPT`
* `:_content-type: PROCEDURE`
* `:_content-type: REFERENCE`

See, xref:assembly-file-metadata[Assembly file metadata] and xref:module-file-metadata[Module file metadata].

== Naming conventions for directories

Use lowercase. For directory with a multiple-word name, use lowercase separated by dash, for example `multicloud-gitops`.

== Language and grammar
Consider the following guidelines:

* Use present tense.
* Use active voice.
* Use second person perspective (you).
* Avoid first person perspective (I, we, us).
* Be gender neutral.
* Use the appropriate tone.
* Write for a global audience.

== Titles and headings
Use sentence-style capitalization in all titles and section headings. Ensure that titles focus on customer tasks instead of the product.

For assemblies and procedure modules, use a gerund form in headings, such as:

* Creating
* Managing
* Using

For modules that do not include any procedure, use a noun phrase, for example _Red Hat Process Automation Manager API reference_.

//=== Discrete headings (commenting out for now. might need it later)

//If you have a section heading that you do not want to appear in the TOC (like if you think that some section is not worth showing up or if there are already too many nested levels), you can use a discrete (or floating) heading:

//http://asciidoctor.org/docs/user-manual/#discrete-or-floating-section-titles

//A discrete heading also will not get a section number in the Customer Portal build of the doc. Previously, we would use plain bold mark-up around a heading like this, but discrete headings also allow you to ignore section nesting rules (like jumping from a `==` section level to a `====` level if you wanted for some style reason).

//To use a discrete heading, just add `[discrete]` to the line before your unique ID. For example:

//----
//[discrete]
//[id="managing-authorization-policies_{context}"]
//== Managing authorization policies
//----

== Writing assemblies

For more information about forming assemblies, see the
link:https://redhat-documentation.github.io/modular-docs/#forming-assemblies[Red Hat modular docs reference guide] and the link:https://raw.githubusercontent.com/redhat-documentation/modular-docs/master/modular-docs-manual/files/TEMPLATE_ASSEMBLY_a-collection-of-modules.adoc[assembly template].

[id="assembly-file-metadata"]
=== Assembly file metadata
Every assembly file should contain the following metadata at the top, with no line spacing in between, except where noted:

----
:_content-type: ASSEMBLY                                        <1>
[id="<unique-heading-for-assembly>"]                            <2>
= Assembly title                                                <3>
include::_common-docs/common-attributes.adoc[]                  <4>
:context: <unique-context-for-assembly>                         <5>
                                                                <6>
:toc:                                                           <7>
----

<1> The content type for the file. For assemblies, always use `:_content-type: ASSEMBLY`. Place this attribute before the anchor ID or, if present, the conditional that contains the anchor ID.
<2> A unique anchor ID for this assembly. Use lowercase. Example: cli-developer-commands
<3> Human readable title (notice the '=' top-level header)
<4> Includes attributes common to Validated Patterns docs.
<5> Context used for identifying headers in modules that is the same as the anchor ID. Example: cli-developer-commands.
<6> A blank line. You *must* have a blank line here before the toc.
<7> The table of contents for the current assembly.

After the heading block and a single whitespace line, you can include any content for this assembly.


== Writing modules
For more information about creating modules, see the https://redhat-documentation.github.io/modular-docs/#_creating_modules[Red Hat Modular documentation reference guide].

[id="module-file-metadata"]
=== Module file metadata
Every module should be placed in the modules folder and should contain the following metadata at the top:

----
// * list of assemblies where this module is included              <1>

:_content-type: <TYPE>                                             <2>
[id="<module-anchor>_{context}"]                                   <3>
= Module title                                                     <4>
----

<1> The content type for the file. Replace `<TYPE>` with the actual type of the module, `CONCEPT`, `REFERENCE`, or `PROCEDURE`. Place this attribute before the anchor ID or, if present, the conditional that contains the anchor ID.
<2> List of assemblies in which this module is included.
<3> A module anchor with {context} that must be lowercase and must match the module's file name. The `{context}` variable must be preceded by an underscore (`_`) when declared in an anchor ID.
<4> Human readable title. To ensure consistency in the results of the
leveloffset values in include statements, you must use a level one heading
( = ) for the module title.

Example:

----
// Module included in the following assemblies:
//
// * cli_reference/developer-cli-commands.adoc

:_content-type: REFERENCE
[id="cli-basic-commands_{context}"]
= Basic CLI commands
----

[id="attribute-files"]
== Attribute files

AsciiDoc attributes are variables you can use in common files to:

* avoid hard-coding brand-specific information,

* share content between multiple brands more easily.

All attribute files must be placed in the a separate attributes file. For example, `common-docs` directory.

It is acceptable to group related attributes in the `common-attributes.adoc` file under a comment, as shown in the following example:

----
//ACM
rh-rhacm-product: Red Hat Advanced Cluster Management (RHACM)
:rh-shortname: RHACM
//GitOps
:gitops-product: Red Hat OpenShift GitOps
:gitops-shortname: GitOps
----

For more information on attributes, see link: https://docs.asciidoctor.org/asciidoc/latest/key-concepts/#attributes.

== Formatting
Use the following links to refer to AsciiDoc markup and syntax.

* https://redhat-documentation.github.io/asciidoc-markup-conventions/[AsciiDoc Mark-up Quick Reference for Red Hat Documentation]

* https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc Syntax Quick Reference]

If you are graduating to AsciiDoc from Markdown, see the https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/#comparison-by-example[AsciiDoc to Markdown syntax comparison by example].

=== Formatting commands and code blocks
To enable syntax highlighting, use `[source,terminal]` for any terminal commands, such as `oc` commands and their outputs. For example:
....
[source,terminal]
----
$ oc get nodes
----
....

To enable syntax highlighting for a programming language, use `[source]` tags used in the code block. For example:

* `[source,yaml]`

* `[source,go]`

* `[source,javascript]`