:_content-type: CONCEPT
:imagesdir: ../../images

[id="letsencrypt-secrets-configuration-in-a-clustergroup"]
= Letsencrypt secrets configuration in a ClusterGroup

The `letsencrypt` parameter configures the use of Letsencrypt for obtaining and managing SSL certificates. This ensures OpenShift clusters have valid SSL certificates, replacing the default self-signed certificates. In regular production environments, clusters are expected to be deployed using an organization’s own certificates, instead of default self-signed ones. Letsencrypt, a popular service providing trusted certificates for web services, eliminates browser security warnings and errors caused by self-signed certificates.

The certificates requested by letsencrypt come from the `global.localClusterDomain` setting.

*Support Level*

* *AWS Only*: Letsencrypt integration is currently supported only on AWS environments within the validated patterns framework. 

.Example:

*Enabling letsencrypt support*

To enable Let's Encrypt support, add the following entries to `values-AWS.yaml` in the pattern root directory. Be sure to adjust the `region:` and `email:` settings as needed:

[source,yaml]
----
letsencrypt:
      region: eu-central-1
      server: https://acme-v02.api.letsencrypt.org/directory
      email: foo@bar.it

    clusterGroup:
      applications:
        letsencrypt:
          name: letsencrypt
          namespace: letsencrypt
          project: default
          path: common/letsencrypt
----


[id="Sub-parameters-letsencrypt"]
== Sub-parameters

* *region*: The AWS region where the cluster is running.

* *server*: The letsencrypt server endpoint for authentication.

* *email*: The e-mail address to use as a DNS contact.


