:_content-type: CONCEPT
:imagesdir: ../../images

[id="understanding-acm-requirements-managed-cluster"]
= Understanding Red Hat Advanced Cluster Management requirements

By default, Red Hat Advanced Cluster Management (RHACM) manages the `clusterGroup` applications that are deployed on all clusters. 

Add a `managedClusterGroup` for each cluster or group of clusters that you want to manage by following this procedure. 

.Procedure

. Switch to your locally created feature branch by running the following command:
+
[source,terminal]
----
$ git checkout my-branch main
----

. In the `value-hub.yaml` file, add a `managedClusterGroup` for each cluster or group of clusters that you want to manage as one. An example `group-one` is provided. 
+
[source,yaml]
----
managedClusterGroups:
  exampleRegion:
    name: group-one
    acmlabels:
      - name: clusterGroup
        value: group-one
    helmOverrides:
      - name: clusterGroup.isHubCluster
        value: false
----
+
The above YAML file segment deploys the `clusterGroup` applications on managed clusters with the label `clusterGroup=group-one`. Specific subscriptions and Operators, applications and projects for that `clusterGroup` are then managed in a `value-group-one.yaml` file. The following is defined for the `clusterGroup=group-one`. 
+
For example:
+
[source,yaml]
----
clusterGroup:
  name: group-one
  isHubCluster: false
  namespaces:
    - config-demo
    - hello-world
    - golang-external-secrets
  # The only subscription on spokes is gitops which gets managed by ACM
  # subscriptions:
  projects:
    - eso
    - config-demo
    - hello-world
  applications:
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: eso
      chart: golang-external-secrets
      chartVersion: 0.1.*
    config-demo:
      name: config-demo
      namespace: config-demo
      project: config-demo
      path: charts/all/config-demo
    hello-world:
      name: hello-world
      namespace: hello-world
      project: hello-world
      path: charts/all/hello-world
----

[IMPORTANT]
====
Ensure that you commit the changes and push them to GitHub so that GitOps can fetch your changes and apply them.
====