
:_content-type: CONCEPT
:imagesdir: ../../images

[id="about-openshift-cluster-sizing-mcg"]
= About OpenShift cluster sizing for the Multicloud GitOps Pattern

For information on minimum hardware requirements for an OpenShift cluster, refer to the {ocp} documentation for link:https://docs.openshift.com/container-platform/3.11/install/prerequisites.html#hardware[System and environment requirements].

To understand cluster sizing requirements for the Multicloud GitOps pattern, consider the following components that the Multicloud GitOps pattern deploys on the datacenter or the hub OpenShift cluster:

|===
| Name | Kind | Namespace | Description

| multicloud-gitops-hub
| Application
| multicloud-gitops-hub
| Hub GitOps management

| Red Hat Advanced Cluster Management
| Operator
| open-cluster-management
| Advance Cluster Management

| Red Hat OpenShift GitOps
| Operator
| openshift-operators
| OpenShift GitOps
|===

The Multicloud GitOps pattern also includes the Red Hat Advanced Cluster Management (RHACM) supporting operator that is installed by OpenShift GitOps using Argo CD.