:_content-type: CONCEPT
:imagesdir: ../../images

[id="med-openshift-cluster-size"]
== About {med-pattern} OpenShift cluster size

The {med-pattern} has been tested with a defined set of configurations that represent the most common combinations that {ocp} customers are using for the x86_64 architecture.

For {med-pattern}, the OpenShift cluster size must be a bit larger to support the compute and storage demands of OpenShift Data Foundations and other Operators.

The minimum requirements for an {ocp} cluster depend on your installation platform. For instance, for AWS, see link:https://docs.openshift.com/container-platform/4.13/installing/installing_aws/preparing-to-install-on-aws.html#requirements-for-installing-ocp-on-aws[Installing {ocp} on AWS], and for bare-metal, see link:https://docs.openshift.com/container-platform/4.13/installing/installing_bare_metal/installing-bare-metal.html#installation-minimum-resource-requirements_installing-bare-metal[Installing {ocp} on bare metal].

For information about requirements for additional platforms, see link:https://docs.openshift.com/container-platform/4.13/installing/installing-preparing.html[{ocp} documentation].


[NOTE]
====
You might want to add resources when more developers are working on building their applications.
====

The OpenShift cluster is a standard deployment of 3 control plane nodes and 3 or more worker nodes.

[cols="^,^,^,^"]
|===
| Node type | Number of nodes | Cloud provider | Instance type

| Control plane and worker
| 3 and 3
| Google Cloud
| n1-standard-8

| Control plane and worker
| 3 and 3
| Amazon Cloud Services
| m5.2xlarge

| Control plane and worker
| 3 and 3
| Microsoft Azure
| Standard_D8s_v3
|===

[role="_additional-resources"]
.Additional resources
* link:https://aws.amazon.com/ec2/instance-types/[AWS instance types]
* link:https://learn.microsoft.com/en-us/azure/virtual-machines/sizes[Azure instance types: Sizes for virtual machines in Azure]
* link:https://cloud.google.com/compute/docs/machine-resource[Google Cloud Platform instance types: Machine families resource and comparison guide]
