:_content-type: PROCEDURE
:imagesdir: ../../../images

[id="deploying-edd-pattern"]
= Deploying the MLOps Fraud Detection pattern

== Prerequisites

. An OpenShift cluster (Go to https://console.redhat.com/openshift/create[the OpenShift console]). Cluster must have a dynamic StorageClass to provision PersistentVolumes.
// See also link:../../mlops-fraud-detection/cluster-sizing[sizing your cluster].
. A GitHub account (and a token for it with repositories permissions, to read from and write to your forks)

For installation tooling dependencies, see link:https://validatedpatterns.io/learn/quickstart/[Patterns quick start].

If you do not have a running Red Hat OpenShift cluster you can start one on a
public or private cloud by using link:https://console.redhat.com/openshift/create[Red Hat's cloud service].

[id="installation"]
= Installing this pattern

. Fork the link:https://github.com/validatedpatterns/mlops-fraud-detection[mlops-fraud-detection] repo on GitHub. It is necessary to fork because your fork will be updated as part of the GitOps and DevOps processes.
. Clone the forked copy of this repository.
+
[source,terminal]
----
git clone git@github.com:<your-username>/mlops-fraud-detection.git
----

. Login to your cluster using oc login or exporting the KUBECONFIG
+
[source,terminal]
----
oc login
----
+
.or set KUBECONFIG to the path to your `kubeconfig` file. For example
+
[source,terminal]
----
export KUBECONFIG=~/my-ocp-env/auth/kubeconfig
----

. Install this pattern on your cluster
+
[source,terminal]
----
./pattern.sh make install
----

The installation will conclude when all the ArgoCD applications installed as part of this pattern are healthy and synced.
