:_content-type: CONCEPT
:imagesdir: ../../images

[id="secret-store-configuration-in-a-clustergroup"]
= Secret store configuration in a ClusterGroup

The `secretStore` parameter defines the configuration for connecting to the secret management backend. This parameter allows the ClusterGroup to interact with the chosen secret storage solution. It is normally configured in the `values-global.yaml` configuration file. The framework provides tools for modifying the secret store configuration.

Many historical patterns have a separate `secretStore key`. However, the new recommendation is to use the `global.secretStore` key instead. In general we recommend using the tools provided to configure a pattern secrets backend, as there are implications to both the hashicorp-vault and golang-external-secrets charts, as well as the clustergroup namespace lists.


[id="sub-parameters-secret-store"]
== Sub-parameters

* *backend*: Specifies the secret store backend, currently supporting “vault”, “kubernetes”, or “none”. The default is “vault.”

* *kind*: This may be “SecretStore” or “ClusterSecretStore”. In most cases, patterns opt for ClusterSecretStore as it enables access from multiple namespaces. “ClusterSecretStore” is the default.


.Examples: 

*In values-global.yaml*:

[source,yaml]
----
global:
  secretStore:
    backend: kubernetes

----

[id="secret-backends"]
== Secrets backends in the Validated Patterns framework

The validated patterns framework currently supports three secrets storage schemes:

* *secrets-backend-vault*: This is the default scheme where the community edition of HashiCorp Vault and the External Secrets Operator are installed. Secrets are stored in vault and then projected into the pattern via External Secrets objects. This approach ensures versionable secrets without exposing them in a Git repository.

* *secrets-backend-kubernetes*: The kubernetes secrets backend also uses the community External Secrets Operator, but rather than injecting secrets into Vault (which is not installed when this backend is selected), secrets are injected into a separate kubernetes namespace. ESO still brokers the projection of these secrets into the pattern.

* *secrets-backend-none*: In this scheme, secret objects are directly injected into the pattern, based on the values-secret configuration. Neither Vault nor the External Secrets Operator are installed. This method is provided for users who require full Red Hat Supportability for their pattern installations.


[id="switching-between-secrets-backends"]
== Switching between secrets backends

The framework provides Makefile-based mechanisms for changing secrets storage schemes. It is recommended to decide on a secrets storage mechanism before installing the pattern.  To configure your pattern with a different secrets storage scheme, run the appropriate make target. This is only necessary if you want to switch from the vault scheme, as all patterns come configured with the vault backend by default. The Makefile targets will modify the values file in your pattern repository, which you must then commit and push to take effect. The changes made by the Makefile targets will be displayed in "diff" format.

.Example:

*Setting backend to Kubernetes for the Ansible Edge GitOps pattern*:

[source,shell]
----

% make secrets-backend-kubernetes
make -f common/Makefile secrets-backend-kubernetes
make[1]: Entering directory '/home/martjack/gitwork/edge/ansible-edge-gitops'
common/scripts/set-secret-backend.sh kubernetes
common/scripts/manage-secret-namespace.sh validated-patterns-secrets present
Namespace validated-patterns-secrets not found, adding
common/scripts/manage-secret-app.sh vault absent
Removing namespace vault
Removing application wth chart location common/hashicorp-vault
common/scripts/manage-secret-app.sh golang-external-secrets present
diff --git a/values-global.yaml b/values-global.yaml
index e594a84..adbd0fa 100644
--- a/values-global.yaml
+++ b/values-global.yaml
@@ -1,15 +1,14 @@
 ---
 global:
   pattern: ansible-edge-gitops
-
   options:
     useCSV: false
     syncPolicy: Automatic
     installPlanApproval: Automatic
-
   hub:
     provider: aws
     storageClassName: gp2
-
+  secretStore:
+    backend: kubernetes
 main:
   clusterGroupName: hub
diff --git a/values-hub.yaml b/values-hub.yaml
index ccf662d..463f24b 100644
--- a/values-hub.yaml
+++ b/values-hub.yaml
@@ -2,31 +2,25 @@
 clusterGroup:
   name: hub
   isHubCluster: true
-
   namespaces:
-    - vault
     - golang-external-secrets
     - ansible-automation-platform
     - openshift-cnv
     - openshift-storage
     - edge-gitops-vms
-
+    - validated-patterns-secrets
   subscriptions:
     aap-operator:
       name: ansible-automation-platform-operator
       namespace: ansible-automation-platform
-
     openshift-virtualization:
       name: kubevirt-hyperconverged
       namespace: openshift-cnv
-
     openshift-data-foundation:
       name: odf-operator
       namespace: openshift-storage
-
   projects:
     - hub
-
   imperative:
     jobs:
       - name: deploy-kubevirt-worker
@@ -52,36 +46,25 @@ clusterGroup:
           - get
           - list
           - watch
-
   applications:
     aap:
       name: ansible-automation-platform
       project: hub
       path: charts/hub/ansible-automation-platform
-
     aap-config:
       name: aap-config
       project: hub
       path: charts/hub/aap-config
-
-    vault:
-      name: vault
-      namespace: vault
-      project: hub
-      path: common/hashicorp-vault
-
     golang-external-secrets:
       name: golang-external-secrets
       namespace: golang-external-secrets
       project: hub
       path: common/golang-external-secrets
-
     openshit-cnv:
       name: openshift-cnv
       namespace: openshift-cnv
       project: hub
       path: charts/hub/cnv
-
     odf:
       name: odf
       namespace: openshift-storage
@@ -89,12 +72,10 @@ clusterGroup:
       path: charts/hub/openshift-data-foundations
       extraValueFiles:
         - '/overrides/values-odf-{{ $.Values.global.clusterPlatform }}-{{ $.Values.global.clusterVersion }}.yaml'
-
     edge-gitops-vms:
       name: edge-gitops-vms
       namespace: edge-gitops-vms
       project: hub
       path: charts/hub/edge-gitops-vms
-
   # Only the hub cluster here - managed entities are edge nodes
   managedClusterGroups: []
Secrets backend set to kubernetes, please review changes, commit, and push to activate in the pattern
make[1]: Leaving directory '/home/martjack/gitwork/edge/ansible-edge-gitops'

----

*Setting backend to none in Ansible Edge GitOps*: 

[source,shell]
----

% make secrets-backend-none      
make -f common/Makefile secrets-backend-none
make[1]: Entering directory '/home/martjack/gitwork/edge/ansible-edge-gitops'
common/scripts/set-secret-backend.sh none
common/scripts/manage-secret-app.sh vault absent
Removing namespace vault
Removing application wth chart location common/hashicorp-vault
common/scripts/manage-secret-app.sh golang-external-secrets absent
Removing namespace golang-external-secrets
Removing application wth chart location common/golang-external-secrets
common/scripts/manage-secret-namespace.sh validated-patterns-secrets absent
Removing namespace validated-patterns-secrets
diff --git a/values-global.yaml b/values-global.yaml
index e594a84..62d43c8 100644
--- a/values-global.yaml
+++ b/values-global.yaml
@@ -1,15 +1,14 @@
 ---
 global:
   pattern: ansible-edge-gitops
-
   options:
     useCSV: false
     syncPolicy: Automatic
     installPlanApproval: Automatic
-
   hub:
     provider: aws
     storageClassName: gp2
-
+  secretStore:
+    backend: none
 main:
   clusterGroupName: hub
diff --git a/values-hub.yaml b/values-hub.yaml
index ccf662d..b9e168e 100644
--- a/values-hub.yaml
+++ b/values-hub.yaml
@@ -2,31 +2,23 @@
 clusterGroup:
   name: hub
   isHubCluster: true
-
   namespaces:
-    - vault
-    - golang-external-secrets
     - ansible-automation-platform
     - openshift-cnv
     - openshift-storage
     - edge-gitops-vms
-
   subscriptions:
     aap-operator:
       name: ansible-automation-platform-operator
       namespace: ansible-automation-platform
-
     openshift-virtualization:
       name: kubevirt-hyperconverged
       namespace: openshift-cnv
-
     openshift-data-foundation:
       name: odf-operator
       namespace: openshift-storage
-
   projects:
     - hub
-
   imperative:
     jobs:
       - name: deploy-kubevirt-worker
@@ -52,36 +44,20 @@ clusterGroup:
           - get
           - list
           - watch
-
   applications:
     aap:
       name: ansible-automation-platform
       project: hub
       path: charts/hub/ansible-automation-platform
-
     aap-config:
       name: aap-config
       project: hub
       path: charts/hub/aap-config
-
-    vault:
-      name: vault
-      namespace: vault
-      project: hub
-      path: common/hashicorp-vault
-
-    golang-external-secrets:
-      name: golang-external-secrets
-      namespace: golang-external-secrets
-      project: hub
-      path: common/golang-external-secrets
-
     openshit-cnv:
       name: openshift-cnv
       namespace: openshift-cnv
       project: hub
       path: charts/hub/cnv
-
     odf:
       name: odf
       namespace: openshift-storage
@@ -89,12 +65,10 @@ clusterGroup:
       path: charts/hub/openshift-data-foundations
       extraValueFiles:
         - '/overrides/values-odf-{{ $.Values.global.clusterPlatform }}-{{ $.Values.global.clusterVersion }}.yaml'
-
     edge-gitops-vms:
       name: edge-gitops-vms
       namespace: edge-gitops-vms
       project: hub
       path: charts/hub/edge-gitops-vms
-
   # Only the hub cluster here - managed entities are edge nodes
   managedClusterGroups: []
Secrets backend set to none, please review changes, commit, and push to activate in the pattern
make[1]: Leaving directory '/home/martjack/gitwork/edge/ansible-edge-gitops'

----


