[id="contributing-to-docs-contributing"]
= Contribute to Hybrid Cloud Patterns documentation
:icons:
:toc: macro
:toc-title:
:toclevels: 1
:description: Contribute to Hybrid Cloud Patterns documentation
:imagesdir: ../images

toc::[]

== Different ways to contribute

There are a few different ways you can contribute to Hybrid Cloud Patterns documentation:

* Email the Hybrid Cloud Patterns team at `<>@redhat.com`.
* Create a link:https://github.com/hybrid-cloud-patterns/docs/issues[GitHub] or link:https://issues.redhat.com/projects/MBP/issues[Jira issue] .
* Submit a pull request (PR). To create a PR, create a local clone of your own fork of the link:https://github.com/hybrid-cloud-patterns/docs[Hybrid Cloud Patterns docs repository], make your changes, and submit a PR. This option is best if you have substantial changes. For more details on creating a PR see <topic_link_to_contribution_workflow>.

== Contribution workflow

When you submit a PR, the [Hybrid Cloud Patterns Docs team] reviews the PR and arranges further reviews by Quality Engineering (QE), subject matter experts (SMEs), and others, as required. If the PR requires changes, updates, or corrections, the reviewers add comments in the PR. When the PR has been reviewed, all updates are complete, and all commits are squashed, the documentation team merges the PR.


== Repository organization

//Placeholder to explain how assemblies, modules, images, common/attribute folders are organized.

----
├── assemblies
│   └── multicloud-gitops-architecture.adoc
├── modules
│   └── multicloud-gitops-logical-architecture.adoc
│   └── multicloud-gitops-physical-architecture.adoc
├── common-attributes
│   └── common_attributes.adoc
├── snippets
│   └── common-snippets.adoc
├── images
│    └── hybrid-multicloud-management-gitops-hl-arch.png
└── README.adoc

----

== Next steps
* link:tools_and_setup.adoc[Install and set up the tools and software]
on your workstation so that you can contribute.
* link:doc_guidelines.adoc[Review the documentation guidelines] to
understand some basic guidelines to keep things consistent
across our content.
