---
 date: 2025-01-09
 title: AGOF v2
 summary: New features and options available in AGOF for Version 2
 author: Martin Jackson
 blog_tags:
 - patterns
 - how-to
 - ansible
 - ansible edge gitops
 - federated edge observability
---
:toc:
:imagesdir: /images

== Overview

The release of Ansible Automation Platform v2.5 has prompted a number of changes
in how the Validated Patterns framework interacts with it as a product. Most of
these changes were prompted by changes in the architecture of AAP itself, but as
a side-effect of those changes we have been able to generalize several aspects of
the Validated Patterns approach to Ansible and hopefully provide better options
across the ecosystem.

To this end, AGOF continues to provide an experience to install Ansible Automation
Platform into AWS

== Introduction

Since very nearly the beginning of the Validated Patterns initiative, we have
been very interested in the inclusion of other frameworks in addition to Kubernetes
and OpenShift as targets for GitOps methodologies, and tools in addition to ArgoCD
as means to apply those methodologies.

To this end, one of the earliest Validated Patterns was 
https://validatedpatterns.io/patterns/ansible-edge-gitops/[Ansible Edge GitOps].
One of the driving motivations there was to show that GitOps as a methodology and
practice is applicable to RHEL targets as well, and that Ansible Automation Platform
can be the GitOps controller that applies a known, desired state configuration (in
this case to VMs).

In the time since Ansible Edge GitOps was first developed, the strategic significance
of OpenShift Virtualization has increased. Ansible Automation Platform has grown
significantly in capabilities and features, introducing the Automation Hub and Event-Driven
Ansible components. The maturity and adoption of the Ansible Configuration as Code tools
have similarly improved.

Further, one of the consistent pieces of feedback we received about Ansible Edge GitOps
was some variation of "How is VMs running in AWS 'Edge'?" This was a very fair point; the
reason we implemented the pattern that way was because we did not want users to be required
to supply their own devices to be able to run the pattern and see it in action. However, the
path we chose for that also effectively precluded users from being able to easily run the
pattern against physical devices if they did have them. And while it was possible, in theory,
to extract the HMI demo component from the pattern, it was difficult. In short, the pattern
was too monolithic and thus too hard to customize.

With the release of Ansible Automation Platform 2.5, and an invitation to work on a problem
related to the initial Ansible Edge GitOps problem set (Ansible Edge focused on the application
delivery and configuration use case), we had an opportunity to re-examine the underlying
architecture of the pattern and see if we could improve on it. The result is Federated Edge
Observability, which focuses on a solution to manage remote edge nodes, including telemetry
collection, federation, and visualization components.

== New Features

AGOF v2 now supports installation and configuration of Ansible Automation Platform 2.5.

AGOF v2 now directly supports configuration of AAP inside OpenShift via a chart that is
published in the Validated Patterns chart repository. Inside an OpenShift Validated Pattern,
an Ansible Validated Pattern can make use of the HashiCorp Vault instance that the OpenShift
Validated Pattern uses for secret storage to store secrets for AAP as well.

== Removals

The transition from AAP 2.4 to AAP 2.5 represents a much larger jump than one might think
based on SemVer numbering. (Note: Ansible Automation Platform does not claim adherence
to the SemVer standard.)

The main thing that impacts AGOF is the addition of the Platform or Gateway API. This enables
a number of useful features, but represents a radical departure from the installation scheme
that was used previously for the containerized installer, which was the focus of AGOF installations.
The new gateway API allows all of the AAP components to function on a single server as a unified
whole, as opposed to each service running on the same server but without essential knowledge of
other services that might be running on the same node. This also meant that in a typical single-node
containzerized install, none of the services would be listening on the "normal" HTTPS port (443),
which may have been surprising.

The AAP Gateway component now functions as a gateway layer, that brokers access to the other
components of Ansible Automation Platform. The Gateway listens on port 443 and dispatches
requests to the various components as appropriate. Further, the role-based access control (RBAC)
components of AAP have moved into the Gateway component, which allows for a more coherent
approach to RBAC, but results in some changes that are not backwards compatible with previous
versions. Further, the AAP Operator as it installs on OpenShift has seen substantial development
and partly due to the Gateway, has been changed in ways that are not always backwards compatible
with version 2.4 and previous.

Because previous versions of AGOF (v1) support AAP versions 2.4 and below, and because it is
reasonable to expect that future versions of AAP will follow the 2.5 architecture, we made the
decision that AGOF v2 would drop support for AAP 2.4 and below, and only support AAP 2.5 and
subsequent releases.

Additionally, several elements that were initially included in AGOF as shims for what would
eventually become RHIS-builder have now been removed. These were undocumented code bits that
allowed for using the AGOF codebase to configure Red Hat Satellite and Red Hat Identity
Management as part of the AGOF bootstrap. These options were never fully documented, never
formally tested, and upon further architectural review, did not belong in AGOF proper. Thus
they have been removed.

== Changes in AAP Architecture

Before AAP 2.5, all of the major components of AAP were managed separately, by their own dedicated
collections for configuration. Controller, Event-Driven Ansible, and Automation Hub had their
own APIs, their own databases, and their own RBAC models.

As of 2.5, there is a new Gateway layer that handles routing into the various AAP components as well
as providing RBAC for all of the other platform components. This required refactoring several elements
of the other configuration collections. Upstream, the configuration-as-code collections decided
to re-package the configuration as code tooling to more closely resemble the new architecture; this
especially includes the introduction of the infra.aap_configuration collection which can configure the 
entire product, and sequences the configuration of the components correctly. Previously, users of the 
tooling had to use three different collections to configure the entire product.

Most technically significant for AGOF, the dependencies for the infra.aap_configuration collection are 
only available from the Ansible Automation Hub, which requires a Red Hat offline token to access. This
required changes in how Validated Patterns in general handled AAP configuration, because previously
Validated Patterns used the upstream collections to do AAP configuration. The changes in collection
packaging required Validated Patterns to be able to bootstrap an environment suitable for complete AAP
configuration. (Ansible Edge GitOps only required the use of the Controller component of AAP, and only
explicitly provided a mechanism to configure Controller. It was possible to configure the other components
of AAP via this mechanism, but doing so would have been far from straightforward.)

AGOF already provided a mechanism for integrating with Automation Hub content, so it made sense to extend
that mechanism to work with OpenShift-based installations of AAP in addition to the single-node 
Containerized Installation, which was its initial focus. This also had the benefit of making any use of
Ansible as a GitOps agent in Validated Patterns more easily transferable outside of OpenShift.

It also exposed some bad assumptions that were built into Ansible Edge GitOps, which becane apparent when
making these updates.

== Bad Assumptions (and How We Fixed Them)

One of the initial challenges with the interface between Kubernetes and the VM world in Ansible Edge GitOps
was how to get access to the various resources in the Kubernetes cluster. Since the Validated Patterns framework
needs and has access to the initial administrative Kubeconfig for the OpenShift cluster, it was convenient
to absorb that into the AAP configuration and just use that to discover anything needed. It was convenient,
but it was also (on reflection) a violation of the "least-privilege" principle, which states that systems
should only get the access they need to accomplish their tasks. The Kubeconfig access was used to discover
service objects in another namespace, and couple potentially have altered them, or anything else in the cluster.

This only became really obvious when the AAP configuration had to be done outside the context of the initial
Validated Patterns bootstrap environment. In AGOF v2, and in the Helm chart for using AGOF in Validated Patterns,
this has been addressed by including a specific service account and RBAC that allows for VM service discovery
by default.

== OpenShift Support

OpenShift support for AGOF works by creating a "clean room" environment for AGOF within the cluster that hosts
the Ansible Automation Platform operator. The scheme expects that the AAP installation will be running but 
otherwise unconfigured. The chart will then apply an Ansible Validated Pattern (in the form an Ansible
configuration-as-code set of repositories) to run on the in-cluster AAP controller. The configuration of AAP
will run periodically, every 10 minutes by default, so that if any change is made to either AGOF or to the pattern
those changes will be reflected and applied in the next run.

For use in this scenario, new Makefile targets have been introduced. The key one used for the OpenShift scheme is
`openshift_vp_install`, which can also be run outside OpenShift.

In addition to downloading and installing the collections necessary to configure AAP, the pre-init also sets up
a specific override scheme, which integrates and embeds the variables passed to the helm chart into the Ansible
Validated Pattern.

== agof_vault.yml and agof_overrides.yml

The AGOF chart uses the in-cluster Vault instance for the secrets it needs, primarily a vault file (which may
contain an arbitrary amount of secrets and, if the user wishes, non-secret data), and the chart will create an
agof_overrides.yml file which contains the specific coordinates of both the AGOF repo and version, as well as
all helm chart values that have been set by the user. This allows the user to include extra data in the AGOF
chart that can be passed through to the AAP instance configuration.

Nothing critical needs to be stored in the agof_vault.yml file - it is quite possible to specify "---" (that is,
an empty YAML file) as its contents. However, if there are other secrets that the Ansible pattern needs that
are not going to be injected into Vault for some reason, the vault file is the place to put them.

== Secrets "layering"

In the AGOF on OpenShift chart, agof_vault.yml is passed as an extravars file, and then agof_overrides.yml
is passed as another extravars file. This makes the override characteristics of variables that may be used
in both files deterministic - anything set in agof_overrides.yml will override any value set in the vault file.
This was done to ensure that values that users may be accustomed to setting in the vault file - such as the
infrastructure-as-code repository - would definitely be overridden by the overrides file.
be overridden

== AGOF v2: Repositories for a Pattern and their Purposes

== Charts for Ansible Validated Patterns

== In Action: Federated Edge Observability

Please see the companion blog article that provides a detailed walkthrough of the Federated Edge Observability
Validated Pattern that demonstrates these concepts, and please feel free to use these new pattern capabilities
in your own patterns.
