---
title: Cluster sizing
weight: 30
aliases: /multicloud-gitops-qat/mcg-qat-cluster-sizing/
---

include::modules/comm-attributes.adoc[]

:toc:
:imagesdir: /images
:_content-type: ASSEMBLY

[id="about-openshift-cluster-sizing-mcg"]
== About OpenShift cluster sizing for the {qat-mcg-pattern}

The minimum requirements for an {ocp} cluster depend on your installation platform, for example:

* For AWS, see link:https://docs.openshift.com/container-platform/4.13/installing/installing_aws/preparing-to-install-on-aws.html#requirements-for-installing-ocp-on-aws[Installing {ocp} on AWS].

* For bare-metal, see link:https://docs.openshift.com/container-platform/4.13/installing/installing_bare_metal/installing-bare-metal.html#installation-minimum-resource-requirements_installing-bare-metal[Installing {ocp} on bare metal].

To understand cluster sizing requirements for the {qat-mcg-pattern}, consider the following components that the {qat-mcg-pattern} deploys on the datacenter or the hub OpenShift cluster:

|===
| Name | Kind | Namespace | Description

| multicloud-gitops-qat-hub
| Application
| multicloud-gitops-qat-hub
| Hub GitOps management

| Red Hat Advanced Cluster Management
| Operator
| open-cluster-management
| Advance Cluster Management

| Red Hat OpenShift GitOps
| Operator
| openshift-operators
| OpenShift GitOps

| Node Feature Discovery
| Operator
| openshift-nfd
| Manages the detection and labeling of hardware features and configuration (for example {intel-qat})

| Red Hat OpenShift Data Foundation
| Operator
| openshift-storage
| Cloud Native storage solution

| Intel Device Plugin®
| Operator
| inteldeviceplugin
| Manages Intel hardware feature-provisioning

| Sail Operator
| Operator
| istio-system
| Istio Service Mesh solution
|===

The {qat-mcg-pattern} also includes the Red Hat Advanced Cluster Management (RHACM) supporting operator that is installed by OpenShift GitOps using Argo CD.

[id="mcg-openshift-datacenter-hub-cluster-size"]
== {qat-mcg-pattern} with OpenShift clusters sizes

The datacenter hub OpenShift cluster needs to be a bit bigger than the Factory/Edge clusters because this is where the developers will be running pipelines to build and deploy the {qat-mcg-pattern} on the cluster. The above cluster sizing is close to a minimum size for a Datacenter HUB cluster. In the next few sections we take some snapshots of the cluster utilization while the {qat-mcg-pattern} is running. Keep in mind that resources will have to be added as more developers are working building their applications.

The recommended clusters sizes for datacenter hub and for managed datacenter are the same in this case:

include::modules/intel-recommended-cluster-sizing-5th-gen-sgx.adoc[]
