---
menu:
  workshop:
    parent: Validated Patterns
title: Patterns Wrapper Script
weight: 54
---

:toc:
include::modules/comm-attributes.adoc[]

== Using the pattern.sh script

[#about]

[source,bash]
----
$ ./pattern.sh

       1          Welcome to the Validate Pattern utility container
      111         It contains all the needed components to install a pattern.
     1   1
    111 111       Please run the following for more information:
   1       1
  111     111       ./pattern.sh make help
 1   1   1   1
111 111 111 111

----

* Used to deploy the pattern from the command-line
* Deploys the operator with a repository and branch from the local clone of the repo
* Provides a way to invoke the container which has all of the pre-requisites software installed (e.g. python, ansible, make)
* Improved User Experience when deploying Patterns from the command line
* When installing a pattern use:

[source,bash]
----
./pattern.sh make install
----
* When loading secrets into your deployment
[source,bash]
----
./pattern.sh make load-secrets
----

IMPORTANT: pattern.sh uses your origin remote and current branch. To change the branch after a deployment, run `make install` in the new branch

[#help]
== Help Menu

`pattern.sh` comes with a help menu, to use it:

[source,bash]
----
$ ./pattern.sh make help

For a complete guide to these targets and the available overrides, please visit https://validatedpatterns.io/blog/2025-08-29-new-common-makefile-structure/

Usage:
  make <target>
  help                                 Print this help message

Pattern Install Tasks
  show                                 Shows the template that would be applied by the `make install` target
  operator-deploy operator-upgrade     Installs/updates the pattern on a cluster (DOES NOT load secrets)
  install                              Installs the pattern onto a cluster (Loads secrets as well if configured)
  uninstall                            (EXPERIMENTAL) See https://validatedpatterns.io/blog/2026-02-16-pattern-uninstall/.
  load-secrets                         Loads secrets onto the cluster (unless explicitly disabled in values-global.yaml)

Validation Tasks
  validate-prereq                      verify pre-requisites
  validate-origin                      verify the git origin is available
  validate-cluster                     Do some cluster validations before installing
  validate-schema                      validates values files against schema in common/clustergroup
  argo-healthcheck                     Checks if all argo applications are synced
----

The link:https://validatedpatterns.io/blog/2025-08-29-new-common-makefile-structure/#_using_makefile_common[link in the help text] describes the available arguments and how to use them for each of
the common Makefile targets.
