---
menu: workshop
title: Pattern Tiers
weight: 40
---

:toc:
include::modules/comm-attributes.adoc[]

== Tiers
[#about]
The different tiers of Validated Patterns are designed to facilitate ongoing maintenance, support, and testing effort for a pattern. To contribute to a pattern that suits your solution or to learn about onboarding your own pattern, understand the following pattern tiers.

|===
|**Tier**|**Description**|**More Information**

|**Sandbox**
a| * entrypoint for onboarding your Pattern
  * able to deploy onto a freshly install OpenShift cluster without modifications or tuning
  * must include a top-level README
| link:/contribute/sandbox/[Details]

|**Tested**
a| * must include a standardized architecture diagram using (or conforming to) the standard Validated Patterns tooling
  * must ensure the test plan passes at least once per quarter
  * must include a written guide for others to follow when demonstrating the platform
| link:/contribute/tested/[Details]

|**Maintained**
a| * functional on all currently supported/extended update support (EUS) versions of OpenShift
  * must fix breakage in a timely manner
  * must document their support policy
| link:/contribute/maintained/[Details]

|===

== Additional Resources
[#resources]

For more details, see the link:/learn/about-pattern-tiers-types/[Pattern Tier Types] page and the link:/learn/implementation[Implementation Requirements] guide.
