---
title: Getting Started
weight: 10
aliases: /multicloud-federated-learning/getting-started/
---

:toc:
:imagesdir: /images
:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

== Deploying the Multicloud Federated Learning Pattern

=== Prerequisites

* Go: Version 1.19 or higher
* Ensure [kubectl](https://kubernetes.io/docs/reference/kubectl/) and [kustomize](https://kubectl.docs.kubernetes.io/installation/kustomize/) are installed.
* Ensure [kind](https://kind.sigs.k8s.io/)(greater than v0.9.0+, or the latest version is preferred) is installed.
* Make: Ensure `make` is installed for build automation
* Optional: Podman or Docker for container image building

=== Set Up the Environment

. Install the `clusteradm` CLI tool:
+
[source,bash]
----
$ curl -L https://raw.githubusercontent.com/open-cluster-management-io/clusteradm/main/install.sh | bash
----

. Create hub and managed clusters using `kind`:
+
[source,bash]
----
$ curl -L https://raw.githubusercontent.com/open-cluster-management-io/OCM/main/solutions/setup-dev-environment/local-up.sh | bash
----
+
Verify the environment
+
[source,bash]
----
$ kubectl get mcl
NAME       HUB ACCEPTED   MANAGED CLUSTER URLS                  JOINED   AVAILABLE   AGE
cluster1   true           https://cluster1-control-plane:6443   True     True        3d22h
cluster2   true           https://cluster2-control-plane:6443   True     True        3d22h
----

. Deploy Federated Learning Controller

.. Clone and navigate to the repository:
+
[source,bash]
----
$ git@github.com:open-cluster-management-io/addon-contrib.git
$ cd federated-learning-controller
----

.. Build and push the controller image (or use pre-built `quay.io/myan/federated-learning-controller:latest`):
+
[source,bash]
----
$ make docker-build docker-push IMG=<IMG> 
----

.. Deploy the controller:
+
[source,bash]
----
# switch the context to hub cluster
$ kubectl config use-context kind-hub

$ make deploy IMG=<controller-image> NAMESPACE=<controller-namespace(default is open-cluster-management)>
----

.. Verify deployment:
+
The federated learning controller is running in the open-cluster-management namespace by default.
+
[source,bash]
----
$ kubectl get pods -n open-cluster-management
NAME                                            READY   STATUS      RESTARTS   AGE
cluster-manager-d9db64db5-c7kfj                 1/1     Running     0          3d22h
cluster-manager-d9db64db5-t7grh                 1/1     Running     0          3d22h
cluster-manager-d9db64db5-wndd8                 1/1     Running     0          3d22h
federated-learning-controller-d7df846c9-nb4wc   1/1     Running     0          3d22h
----

=== Deploy the Application

. build the Federated Learning Application Image
+
*Note*: You can directly use the pre-built image `quay.io/myan/federated-learning-app:latest`.

.. Navigate to the Flower framework example:
+
[source,bash]
----
$ cd federated-learning-controller/examples/flower
----

.. *(Optional)* Modify the model code located in `flower/app-torch`, then build and push the image:
+
[source,bash]
----
$ export REGISTRY=<your-registry>
$ export IMAGE_TAG=<your-image-tag>
$ make build-app-image
$ make push-app-image
----
+
The image will be named `<REGISTRY>/flower-app-torch:<IMAGE_TAG>`.

. Deploy the Application to the Hub Cluster
+
The current server and client use the same image. You can also use the pre-built image `quay.io/myan/flower-app-torch:latest`. After creating the resource, the server will deploy to the hub cluster, and the clients will deploy to managed clusters.
+
[source,yaml]
----
apiVersion: federation-ai.open-cluster-management.io/v1alpha1
kind: FederatedLearning
metadata:
  name: federated-learning-sample
spec:
  framework: flower
  server:
    image: <REGISTRY>/flower-app-torch:<IMAGE_TAG>
    rounds: 3
    minAvailableClients: 2
    listeners:
      - name: server-listener
        port: 8080
        type: LoadBalancer
    storage:
      type: PersistentVolumeClaim
      name: model-pvc
      path: /data/models
      size: 2Gi
  client:
    image: <REGISTRY>/flower-app-torch:<IMAGE_TAG>
    placement:
      clusterSets:
        - global
      predicates:
        - requiredClusterSelector:
            claimSelector:
              matchExpressions:
                - key: federated-learning-sample.client-data
                  operator: Exists
----

. Schedule the Application on Managed Clusters
+
The above configuration schedules only clusters with a `ClusterClaim` having the key `federated-learning-sample.client-data`. You can combine this with other scheduling policies (refer to the Placement API for details).

.. Managed Cluster 1 claims data:
+
[source,bash]
----
$ kubectl config use-context kind-cluster1

$ cat <<EOF | kubectl apply -f -
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ClusterClaim
metadata:
  name: federated-learning-sample.client-data
spec:
  value: /data/private/cluster1
EOF
----

.. Managed Cluster 2 claims data:
+
[source,bash]
----
$ kubectl config use-context kind-cluster2
$ cat <<EOF | kubectl apply -f -
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ClusterClaim
metadata:
  name: federated-learning-sample.client-data
spec:
  value: /data/private/cluster2
EOF
----

. Check the Application Status

.. After creating the instance, the server initially shows a status of `Waiting`:
+
*Hub cluster server example:*
+
[source,bash]
----
$ kubectl get pods
NAME                                            READY   STATUS      RESTARTS   AGE
federated-learning-sample-server-7jnfs          0/1     Completed   0          5d3h
----

.. Once the required clients are ready, status changes to `Running`:
+
*Managed cluster client example:*
+
[source,bash]
----
$ kubectl get pods -n open-cluster-management
NAME                                     READY   STATUS      RESTARTS   AGE
federated-learning-sample-client-75sc8   0/1     Completed   0          5d3h
----

.. After the training and aggregation rounds complete, the status becomes `Completed`:
+
[source,bash]
----
status:
  listeners:
  - address: 172.18.0.2:31166
    name: listener(service):federated-learning-sample-server
    port: 31166
    type: NodePort
  message: Model training successful. Check storage for details
  phase: Completed
----

.. Download and Verify the Trained Model
+
After training is complete and the status is Completed, the MNIST model is saved in the `model-pvc` PersistentVolumeClaim. You can download and evaluate the trained model by following this link:https://github.com/open-cluster-management-io/addon-contrib/blob/main/federated-learning-controller/examples/notebooks/1.hub-evaluation.ipynb[verification notebook].
