---
title: Cluster Sizing
weight: 20
aliases: /medical-diagnosis/cluster-sizing/
---

:toc:
:imagesdir: /images
:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

//AI: Removed the following since we have CI status linked on the patterns page
//[id="tested-platforms-cluster-sizing"]
//== Tested Platforms

//AI: Removed the following in favor of the link to OCP docs
//[id="general-openshift-minimum-requirements-cluster-sizing"]
//== General OpenShift Minimum Requirements

To know the minimum requirements for an {ocp} cluster, for example on bare-metal, see link: https://docs.openshift.com/container-platform/4.13/installing/installing_bare_metal/installing-bare-metal.html#installation-minimum-resource-requirements_installing-bare-metal[Minimum resource requirements for cluster installation].


[id="about-med-diagnosis-components"]
=== About {med-pattern} components

Here's an inventory of what gets deployed by the *Medical Diagnosis* pattern:

|===
| Name | Kind | Namespace | Description

| Medical Diagnosis Hub
| Application
| medical-diagnosis-hub
| Hub GitOps management

| Red Hat OpenShift GitOps
| Operator
| openshift-operators
| OpenShift GitOps

| Red Hat OpenShift Data Foundations
| Operator
| openshift-storage
| Cloud Native storage solution

| Red Hat AMQStreams (Apache Kafka)
| Operator
| openshift-operators
| AMQ Streams provides Apache Kafka access

| Red Hat OpenShift Serverless
| Operator
| - knative-eventing
- knative-serving
| Provides access to knative eventing and serving functions
|===


[id="medical-diagnosis-pattern-openshift-cluster-size-cluster-sizing"]
=== About {med-pattern} OpenShift Cluster Size

The Medical Diagnosis pattern has been tested with a defined set of configurations that represent the most common combinations that Red Hat OpenShift Container Platform (OCP) customers are using or deploying for the x86_64 architecture.

The OpenShift cluster for the *Medical Diagnosis* pattern needs to be sized a bit larger to support the compute and storage demands of OpenShift Data Foundations and other operators that make up the pattern. The above cluster sizing is close to a *minimum* size for an OpenShift cluster supporting this pattern.  In the next few sections we take some snapshots of the cluster utilization while the *Medical Diagnosis* pattern is running.  Keep in mind that resources will have to be added as more developers are working building their applications.

The OpenShift cluster is a standard deployment of 3 control plane nodes and 3 or more worker nodes.

[cols="^,^,^,^"]
|===
| Node Type | Number of nodes | Cloud Provider | Instance Type

| Control Plane/Worker
| 3
| Google Cloud
| n1-standard-8

| Control Plane/Worker
| 3
| Amazon Cloud Services
| m5.2xlarge

| Control Plane/Worker
| 3
| Microsoft Azure
| Standard_D8s_v3
|===

//Removed section for instance types as we did for MCG