---
menu:
  learn:
    parent: Key concepts
title: About applications
weight: 25
---

:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

[id="applications"]
= Applications

The applications section in the Helm values file plays a crucial role in defining and managing the deployment of various applications within an OpenShift cluster. By leveraging Helm charts and adhering to validated patterns, it ensures consistency, best practices, and simplified management, leading to reliable and scalable application deployments.

The path field in each application entry points in the values file points to the location of the Helm chart and associated configuration files. These charts contain the Kubernetes manifests and configuration necessary to deploy the application. Helm charts are used to package Kubernetes applications and manage their deployment in a consistent and reproducible manner.

When these applications are deployed, the following Kubernetes resources are typically created:

* *Deployments*: Define the desired state and replicas for the application's pods.
* *Services*: Expose the application's pods to other services or external traffic.
* *ConfigMaps and Secrets*: Store configuration data and sensitive information.
* *PersistentVolumeClaims (PVCs)*: Request storage resources for the application.
* *Ingress or Routes*: Provide external access to the application.
* *RBAC (Role-Based Access Control)*: Define access permissions and roles.