---
menu:
  learn:
    parent: Workflow
title: Validated Pattern Tiers
weight: 41
aliases: /learn/pattern-tier-overview
---

:toc:

:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

[id="pattern-type"]
== About the Validated Pattern tiers

To know about the patterns that you can contribute and use, understand the following different pattern tiers:

|===
|Pattern tier|Description

|Sandboxed
|A work in progress, might not yet include a demonstration. A Customer business problem has potentially not been identified or fully solved
Might have been manually tested, and on a limited set of platforms
Not yet reviewed by Red{nbsp}Hat


|Tested
|Clear business problem with demo
All components are supportable*, and any Red Hat product usage signed-off by BUs
Test plan (manual or automated) that passes at least once for each new OpenShift minor version within 3 months of GA

|Maintained
|Group 2 plus…
Formal release process with z-streams
CI automation (either weekly or event driven at a similar interval)

|===

