---
menu:
  learn:
    parent: Key concepts
title: ClusterGroups
weight: 22
---

:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

[id="clustergroups"]
= About ClusterGroups

In a validated pattern, a ClusterGroup organizes and manages clusters sharing common configurations, policies, or deployment needs, with the default group initially encompassing all clusters unless assigned elsewhere. Multiple cluster groups within a pattern allow for tailored management, enabling specific configurations and policies based on roles, environments, or locations. This segmentation enhances efficiency, consistency, and simplifies complex environments. In the validated patterns framework, a ClusterGroup is a key entity representing either a single cluster or a collection of clusters with unique configurations, determined by Helm charts and Kubernetes features. Typically, a ClusterGroup serves as the foundation for each pattern, with the primary one named in `values-global.yaml`, often referred to as "hub. ManagedClusterGroups can also be defined, specifying characteristics and policies for additional clusters.

When a managed cluster is joined to to RHACM or a new cluster is deployed with RHACM it should be assigned to at least one clusterGroup
RHACM sees that this managed cluster is part of a clusterGroup and after setting up the cluster, including the RHACM agent on the managed cluster, it then deploys GitOps and provides it the information about the clusterGroup. 
GitOps picks up the associated values file and deploys the Operators and configurations/charts.


Add link to https://validatedpatterns.io/learn/clustergroup-in-values-files/. 
