---
menu: learn
title: Infrastructure
weight: 40
aliases: /infrastructure/
---

:toc:
:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

[id="background"]
== Background

Each validated pattern has infrastructure requirements. The majority of the validated patterns will run Red Hat OpenShift while some parts will run directly on Red Hat Enterprise Linux or (RHEL), more likely, a version of RHEL called RHEL for Edge. It is expected that consumers of validated patterns already have the infrastructure in place using existing reliable and supported deployment tools. For more information and tools head over to https://console.redhat.com/[console.redhat.com]

[id="sizing"]
== Sizing

In this section we provide general minimum sizing requirements for such infrastructure but it is important to review specific requirements for a specific validated pattern. For example, link:/industrial-edge/[Industrial Edge 2.0] employs AI/Ml technology that requires large machine instances to support the applications deployed on OpenShift at the datacenter.
