---
menu:
  learn:
    parent: Validated patterns frameworks
title: Using the Controller Configuration collection 
weight: 25
aliases: /ocp-framework/agof/
---

:toc:
:imagesdir: /images
:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

== Using the Controller Configuration collection

An AGOF pattern for example https://github.com/mhjacks/agof_demo_config is primarily an IaC (infrastructure as code) artifact designed to be used with the `controller_configuration` collections. 

The AGOF (Ansible GitOps Framework) repository  https://github.com/validatedpatterns/agof contains the code and tools needed to set up a new Ansible Automation Platform (AAP) instance. This setup is automated, using Infrastructure as Code (IaC) practices. It also includes some specific preferences to make it easier for others to publicly share and manage this type of infrastructure setup.

This approach ensures the automation controller configuration is version-controlled, dynamic, and reproducible. This method enables deployment automation with minimal manual intervention, which is useful for managing multiple controller instances or different environments in a CI/CD pipeline.

For example for the AGOF minimal configuration demo the file https://github.com/mhjacks/agof_demo_config/blob/main/controller_config.yml is used with Ansible's Controller Configuration Collection, allowing the automation and management of Red Hat Ansible Automation Controller (formerly known as Ansible Tower). 

This file automates the creation, updating, or deletion of Ansible Controller objects (organizations, projects, inventories, credentials, templates, schedules). Sensitive information like passwords and keys are pulled dynamically from vaults, ensuring they are not hardcoded in the configuration. The project’s inventory and playbooks are managed through a Git repository, allowing for continuous integration and delivery (CI/CD) practices. Recurring playbook executions are scheduled automatically, eliminating the need for manual job triggers.

== Key sections and parameters

=== Vault variables

*`orgname_vault: 'Demo Organization'`*:: 
This specifies the organization name stored in a vault for security purposes.

*`controller_username_vault: 'admin'`*:: 
This is the Ansible Controller's username stored in a vault.

*`controller_password_vault: '{{ admin_password }}'`*:: 
The password is fetched dynamically from a vault for security purposes.

=== Dynamic variables

*`controller_username: '{{ controller_username_vault }}'`*:: 
The Ansible Controller username is retrieved from the vault variable.

*`controller_password: '{{ controller_password_vault }}'`*:: 
The password is dynamically fetched from the vault.

=== Project configuration

*`agof_demo_project_name: 'Ansible GitOps Framework Minimal Demo'`*:: 
This variable holds the name of the project being managed in the controller.

*`controller_projects`*:: 
Two projects are defined:
  * One with the name *'Demo Project'*, marked for deletion (`state: absent`).
  * The other is the actual project that will be created, associated with the Git repository hosted on GitHub.

For more information see, link:https://github.com/redhat-cop/controller_configuration/blob/devel/roles/projects/README.md[controller_configuration.projects].

=== Organizations

*`controller_organizations`*:: 
Ensures that the organization, defined in `orgname_vault`, exists within the controller. For more information see, link:https://github.com/redhat-cop/controller_configuration/blob/devel/roles/organizations/README.md[controller_configuration.organizations].

=== Inventory and inventory sources

*`controller_inventories`*:: 
Defines an inventory called *'AGOF Demo Inventory'* under the *'Demo Organization'*. For more information see, link:https://github.com/redhat-cop/controller_configuration/blob/devel/roles/inventories/README.md[controller_configuration.inventories].


*`controller_inventory_sources`*:: 
Configures an inventory source tied to the Git project. The inventory is pulled from source control management (SCM) and associated with credentials for SSH access (`ec2_ssh_credential`). For more information see, link:https://github.com/redhat-cop/controller_configuration/blob/devel/roles/inventory_sources/README.md[controller_configuration.inventory_sources].

=== Job templates

*`controller_templates`*:: 
Two job templates are managed:
  * One named *'Demo Job Template'*, marked for deletion.
  * The other, *'Ping Playbook'*, is tied to a specific playbook (`ping.yml`), inventory, and project, and will use the defined credentials for execution.

For more information see, link:https://github.com/redhat-cop/controller_configuration/blob/devel/roles/job_templates/README.md[controller_configuration.job_templates].

=== Job scheduling

*`controller_schedules`*:: 
Configures a recurring job schedule to run the *'Ping Playbook'* template every 120 minutes. The schedule uses an iCal `RRULE` format. For more information see, link:https://github.com/redhat-cop/controller_configuration/blob/devel/roles/schedules/README.md[controller_configuration.schedules].

=== Credentials

*`controller_credentials`*:: 
A credential named *'ec2_ssh_credential'* is created with SSH access to the EC2 instances using the private key stored at the path specified in `demo_ssh_key_file`. For more information see, link:https://github.com/redhat-cop/controller_configuration/blob/devel/roles/credentials/README.md[controller_configuration.credentials].

=== Job Launching

*`controller_launch_jobs`*:: 
Automatically launches the *'Ping Playbook'* job template within the organization defined in `orgname_vault`. For more information see, link:https://github.com/redhat-cop/controller_configuration/blob/devel/roles/job_launch/README.md[controller_configuration.job_launch].

For more information about the controller configuration see:  

* link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html-single/automation_controller_administration_guide/index[Red Hat Automation Controller Admin Guide]

* link:https://github.com/redhat-cop/controller_configuration[Red Hat Communities of Practice Controller Configuration Collection]
