---
menu:
  learn:
    parent: Validated patterns frameworks
title: Validated pattern structure
weight: 21
aliases: /ocp-framework/structure/
---

:toc:
:imagesdir: /images
:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

== OpenShift framework fundamentals

The OpenShift validated patterns framework uses https://docs.openshift.com/container-platform/latest/cicd/gitops/understanding-openshift-gitops.html[OpenShift GitOps] (ArgoCD) as the primary driver for deploying patterns and keeping them up to date. Validated patterns use Helm charts as the primary artifacts for GitOps. https://helm.sh/[Helm charts] offer a powerful templating mechanism for creating repeatable, automated deployments across various environments, including clouds, data centers, and edge locations.

The framework provides consistency across any cloud provider - public or private. So while you could automate the handling for each of the cloud providers, the framework utilizes one Kubernetes distribution that runs on public or private clouds - the hybrid and/or multi cloud model.

Many Cloud Native Computing Foundation (CNCF) projects use https://operatorframework.io/[Operators] to manage the lifecycle of their service. Whenever possible, validated patterns will make use of these Operators to deploy the application service.

https://www.redhat.com/en/technologies/management/advanced-cluster-management[Red Hat Advanced Cluster Management] (ACM) is primarily used to automate the deployment of edge clusters. It provides subscription information for specific deployment sites.

https://docs.openshift.com/container-platform/4.9/cicd/pipelines/understanding-openshift-pipelines.html[OpenShift Pipelines] is used to automate builds and keep image repositories up to date.

== Pattern directories tour

Examining any of the existing patterns reveals the important organizational part of the validated patterns framework. Let's take a look at a couple of the existing validated patterns: Multicluster GitOps and Industrial Edge.

===  Multicloud GitOps

The Multicloud GitOps approach enables centralized management of multiple cloud deployments across both public and private clouds, including workloads and the secure handling of secrets across environments. This approach is built on patterns that consist of two key components: a "common" element, which serves as a foundational framework shared by nearly all patterns, and a pattern-specific element that builds on the common framework with tailored content. This section focuses on the standardized directory structure used in Multicloud GitOps repositories for validated patterns in multicloud setups. By following the well-structured directory layout illustrated here, teams can streamline deployment processes across clouds, reduce configuration drift, enhance automation, and maintain a single source of truth for both infrastructure and application code.

[source,text]
----
~/g/multicloud-gitops on main ◦ tree -L 2
.
├── ansible
│   └── site.yaml
├── ansible.cfg
├── charts
│   ├── all
│   └── region
├── common
│   ├── ansible
│   ├── Changes.md
│   ├── LICENSE
│   ├── Makefile
│   ├── README.md
│   ├── requirements.yml
│   └── scripts
├── LICENSE
├── Makefile
├── overrides
│   ├── values-AWS.yaml
│   └── values-IBMCloud.yaml
├── pattern-metadata.yaml
├── pattern.sh -> ./common/scripts/pattern-util.sh
├── README.md
├── tests
│   └── interop
├── values-global.yaml
├── values-group-one.yaml
├── values-hub.yaml
├── values-secret-multicloud-gitops.yaml
├── values-secret.yaml.template
└── values-standalone.yaml


11 directories, 20 files
----

First we notice some subdirectories: charts and common, along with `values-` yaml files.

===  Industrial edge

[source,text]
----
~/g/industrial-edge on stable-2.0 ◦ tree -L 2
.
├── ansible
│   ├── files
│   ├── playbooks
│   └── site.yaml
├── ansible.cfg
├── Changes.md
├── charts
│   ├── datacenter
│   └── factory
├── common
│   ├── Changes.md
│   ├── LICENSE
│   ├── Makefile
│   ├── README.md
│   ├── requirements.yml
│   └── scripts
├── docs
│   ├── images
│   └── old-deployment-map.txt
├── LICENSE
├── Makefile
├── overrides
│   ├── values-prod-imagedata.yaml
│   └── values-test-imagedata.yaml
├── pattern-metadata.yaml
├── pattern.sh -> ./common/scripts/pattern-util.sh
├── README.md
├── scripts
│   └── check-pipeline-resources.sh
├── SUPPORT_AGREEMENT.md
├── tests
│   └── interop
├── values-AWS.yaml
├── values-Azure.yaml
├── values-datacenter.yaml
├── values-factory.yaml
├── values-GCP.yaml
├── values-global.yaml
├── values-hub.yaml -> values-datacenter.yaml
└── values-secret.yaml.template

15 directories, 26 files
----

We see the same or similar files in the both patterns directories. 

== The `common` directory

Common is a collection of scripts to start the initial deployment of a pattern using the command line interface. The Makefile contains targets for deploying the pattern. The `Makefile` is the primary entry point for deploying a pattern. To maintain modularity, version control, and independent management, cluster management, deployment utilities, and security and certificate charts are stored in separate repositories under the link:https://github.com/validatedpatterns[Validated Patterns GitHub organization]. Ansible automation or utilities are in the link:https://github.com/validatedpatterns/rhvp.cluster_utils[rhvp.cluster_utils].

== The `charts` directory

This is where validated patterns keep the helm charts for a pattern. The helm charts are used to deploy and manage the various components of the applications deployed at a site. By convention, the charts are broken out by site location. You may see `datacenter`, `hub`, `factory`, or other site names in there.

[NOTE]
====
The site naming convention is flexible, allowing users to modify it to suit their environment. 
====

Each site has sub-directories based on application or library component groupings.

From https://helm.sh/docs/chart_template_guide/getting_started/[Helm documentation:]
_Application charts_ are a collection of templates that can be packaged into versioned archives to be deployed.

_Library charts_ provide useful utilities or functions for the chart developer. They're included as a dependency of application charts to inject those utilities and functions into the rendering
pipeline. Library charts do not define any templates and therefore cannot be deployed.

These groupings are used by OpenShift GitOps to deploy into the cluster. The configurations for each of the components inside an application are synced every three minutes by OpenShift GitOps to make sure that the site is up to date. The configuration can also be synced manually if you do not want to wait up to three minutes. For example for industrial-edge the charts directory looks like this:

[source,text]
----
.
├── datacenter
│   ├── data-science-cluster
│   ├── data-science-project
│   ├── manuela-data-lake
│   ├── manuela-tst
│   └── pipelines
└── factory
    └── manuela-stormshift
----
The configuration YAML for each component of the application is stored in the templates subdirectory. 

[source,text]
----
.
├── data-science-cluster
│   ├── Chart.yaml
│   ├── kustomization.yaml
│   ├── templates
│   └── values.yaml
├── data-science-project
│   ├── Chart.yaml
│   ├── kustomization.yaml
│   ├── templates
│   └── values.yaml
├── manuela-data-lake
│   ├── Chart.yaml
│   ├── Kafka2S3Route.java
│   ├── templates
│   └── values.yaml
├── manuela-tst
│   ├── Chart.yaml
│   ├── Kafka2S3Route.java
│   ├── MQTT2KafkaRoute.java
│   ├── templates
│   └── values.yaml
└── pipelines
    ├── Chart.yaml
    ├── extra
    ├── images
    ├── README.md
    ├── templates
    └── values.yaml
----

== The `scripts` directory

In some cases, an Operator or Helm chart may require additional configuration. When extra code is needed for deployment, it should be placed in the scripts directory. Typically, consumers of a validated pattern won't interact directly with these scripts, as they are executed by the existing automation (for example through the Makefile or OpenShift GitOps). If extra adjustments are required for your application, place the scripts here and run them through automation. The scripts directory should generally be treated as off-limits unless you're modifying the framework itself.

== Applications and `values-` files

Helm uses `values.yaml` files to pass variables into charts. Variables in the `values.yaml` file can be overridden in the following ways:

. By a `values.yaml` file in the parent directory
. By a values file passed into the `helm <install/upgrade>` command using `-f`
. By specifying an override individual value in the the `helm` command with `--set`

For more information on values files and their usage see the https://helm.sh/docs/chart_template_guide/values_files/[values files section] of the Helm documentation.

This section is meant as an introduction to the `values-` files that the framework uses to override values in the chart templates. In the Getting Started pages there will be more specific usage details.

=== There are three types of `value-` files.

. *`values-global.yaml`*:
This is used to set variables for helm charts across the pattern. It contains the name of the pattern and sets some other variables for artifacts like, image registry, Git repositories, GitOps syncPolicy etc.
. *`values-<site>.yaml`*:
Each specific site requires information regarding what applications and subscriptions are required for that site. This file contains a list of namespaces, applications, subscriptions, the operator versions etc. for that site.
. *`values-secret.yaml.template`*:
All patterns require some secrets for artifacts included in the pattern. For example credentials for GitHub, AWS, or Quay.io. The framework provides a safe way to load those secrets into a vault for consumption by the pattern. This template file can be copied to your home directory, the secret values applied, and the validated pattern will go look for `values-secrets.yaml` in your home directory. *Do not leave a `values-secrets.yaml` file in your cloned git directory or it may end up in your (often public) Git repository, like GitHub.*
+
[NOTE]
====
This file has nothing to do with helm and can be copied either to your home directory or to the `~/.config/validatedpatterns/` folder. The naming should be `values-secret-<pattern-name>.yaml`. Ideally it should be encrypted with the ansible-vault.
====

=== Values files can have some overrides.

. Version overrides can be used to set specific values for OCP versions. For example *`values-hub-4.16.yaml`* allows you to tweak a specific value for OCP 4.16 on the Hub cluster.
. Version overrides can be used to set specific values for specific cloud providers. For example *`values-AWS.yaml`* would allow you to tweak a specific value for all cluster groups deployed on AWS.

=== Other combination examples include:

. *`values-hub-Azure.yaml`* only apply this Azure tweak on the hub cluster.
. *`values-4.16.yaml`* apply these OCP 4.16 tweaks to all cluster groups in this pattern.

Current supported cloud providers include *`AWS`*, *`Azure`*, *`GCP`*, and *Nutanix*.

== Environment values and Helm

The purpose of the values files is to leverage Helm's templating capabilities, allowing you to dynamically substitute values into your charts. This makes the pattern very portable.

The following `messaging-route.yaml` example shows how the AMQ messaging service is using values set in the `values-global.yaml` file for Industrial Edge.

[source,yaml]
----
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: messaging
  name: messaging
spec:
  host: messaging-manuela-tst-all.apps.{{ .Values.global.datacenter.clustername }}.{{ .Values.global.datacenter.domain }}
  port:
    targetPort: 3000-tcp
  to:
    kind: Service
    name: messaging
    weight: 100
  wildcardPolicy: None
----

The values in the `values-global.yaml` will be substituted when the YAML is applied to the cluster.

[source,yaml]
----
global:
  pattern: industrial-edge

...

  datacenter:
    clustername: ipbabble-dc
    domain: blueprints.rhecoeng.com

  edge:
    clustername: ipbabble-f1
    domain: blueprints.rhecoeng.com
----