---
menu:
  learn:
    parent: Validated patterns frameworks
title: Structuring a validated pattern
weight: 22
aliases: /ocp-framework/structure-a-pattern/
---

:toc:
:imagesdir: /images
:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

== Creating a validated pattern

The high level steps to create a validated pattern are as follows: 

1. Identify the business case you want to address.  
2. Use the Multicloud GitOps as a starting point by using the template to create a new Git repository in your local GitHub account.  
3. Identify the technology components that you need.  In the case of an existing demo you might already know which components are part of the pattern.  
4. Ensure that the configuration of those components, and the integration points are handled in the pattern.  


== Best Practices for Creating Validated Patterns

1. *Start with OpenShift Multicloud GitOps*: When creating a validated pattern, begin with OpenShift Multicloud GitOps as your foundation. This is the most fundamental pattern and should serve as your base.

2. *Extend the base pattern with On-Site assets*: Build on the base pattern by integrating assets developed on-site. These assets might include Helm charts or Kustomize manifests. Ensure that everything required to deploy the pattern, including the desired state and configuration of resources, is included in the repository.

3. *Embed additional commands into manifests*: If you find yourself frequently executing `oc apply` or similar commands, incorporate these actions into the appropriate manifests within the pattern. This will help streamline and automate the deployment process.

4. *Separate configuration from development sources*: Maintain a clear separation between configuration settings and development source code. This practice ensures better organization and makes it easier to manage configurations independently from the application code.