---
menu: learn
title: Workflow
weight: 60
aliases: /workflow/
---

:toc:
:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

= Workflow

Patterns are designed to be composed of multiple components, that consumers and contributors can integrate into GitOps workflows. For instance, the link:/industrial-edge[Industrial Edge]  pattern comprises a https://github.com/validatedpatterns/industrial-edge[repository] with pattern-specific logic and configuration, alongside a https://github.com/validatedpatterns/common[common repository] containing elements common to various patterns. This common repository is included as a subtree within each pattern repository, streamlining consistency and reusability across different patterns.


[id="consuming-a-pattern"]
== Consuming a pattern

. Fork the pattern repository on GitHub to your workspace (GitHub user or organization). Forking is necessary because your fork updates as part of the GitOps and DevOps processes, and the main branch (by default) is used in the automated workflows.
. Clone the forked repository:
+
`git clone git@github.com:<your-workspace>/industrial-edge.git`

. Create a local copy of the Helm values file to safely include credentials.
+
[NOTE]
====
Do not commit this file as it may contain sensitive credentials.
====
+
[source,terminal]
----
$ cp values-secret.yaml.template ~/values-secret.yaml
$ vi ~/values-secret.yaml
----

. Customize the deployment for your cluster.
+
[source,terminal]
----
$ vi values-global.yaml
$ git commit values-global.yaml
$ git push
----

