---
menu: learn
title: Workflow
weight: 60
aliases: /workflow/
---

:toc:
:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

= Workflow

Patterns are designed to be composed of multiple components, that consumers and contributors can integrate into GitOps workflows. For instance, the link:/industrial-edge[Industrial Edge]  pattern comprises a https://github.com/validatedpatterns/industrial-edge[repository] with pattern-specific logic and configuration, alongside a https://github.com/validatedpatterns/common[common repository] containing elements common to various patterns. This common repository is included as a subtree within each pattern repository, streamlining consistency and reusability across different patterns.


[id="consuming-a-pattern"]
== Consuming a pattern

. Fork the pattern repository on GitHub to your workspace (GitHub user or organization). Forking is necessary because your fork updates as part of the GitOps and DevOps processes, and the main branch (by default) is used in the automated workflows.
. Clone the forked repository:
+
`git clone git@github.com:<your-workspace>/industrial-edge.git`

. If you want to customize credentials, create a local copy of the secrets values file. Do not push the secrets file to GitHub.

.. Create a local copy of the secrets template file:
[source,terminal]
+
----
$ cp values-secret.yaml.template ~/values-secret.yaml
----
.. Edit the file and securely add your cluster-specific credentials:
+
[source,terminal]

----
$ vi ~/values-secret.yaml
---- 

. Customize the deployment for your cluster. Customization involves updating the `values-global.yaml` file with configurations specific to your cluster environment.
.. Edit the `values-global.yaml` file:
+
[source,terminal]
+
----
$ vi values-global.yaml
----
.. Commit the updated `values-global.yaml` file to the repository:
+
[source,terminal]
+
----
$ git commit values-global.yaml
----
.. Push the committed changes:
+
[source,terminal]

----
$ git push
----

