---
title: Getting started
weight: 10
aliases: /rag-quickstart/getting-started/
---

:toc:
:imagesdir: /images
:_content-type: ASSEMBLY
include::modules/comm-attributes.adoc[]

[id="deploying-rag-quickstart-pattern"]
== Deploying the RAG AI Quickstart pattern

.Prerequisites

* An OpenShift cluster (version 4.18 or later)
 ** To create an OpenShift cluster, go to the https://console.redhat.com/[Red Hat Hybrid Cloud console].
 ** Select *OpenShift \-> Red Hat OpenShift Container Platform \-> Create cluster*.
* A https://huggingface.co/[HuggingFace] account with an API token that has read permissions.
 ** You must accept the terms and conditions for the https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct[meta-llama/Llama-3.2-3B-Instruct] model with the account that the API token belongs to.
* The Helm binary. For instructions, see link:https://helm.sh/docs/intro/install/[Installing Helm].
* Additional installation tool dependencies. For details, see link:https://validatedpatterns.io/learn/quickstart/[Patterns quick start].

[id="preparing-for-deployment"]
== Preparing for deployment
.Procedure

. Fork the link:https://github.com/validatedpatterns-sandbox/ai-quickstart-rag[ai-quickstart-rag] repository on GitHub. You must fork the repository to customize this pattern.

. Clone the forked copy of this repository.
+
[source,terminal]
----
$ git clone git@github.com:your-username/ai-quickstart-rag.git
----

. Go to the root directory of your Git repository:
+
[source,terminal]
----
$ cd ai-quickstart-rag
----

. Run the following command to set the upstream repository:
+
[source,terminal]
----
$ git remote add -f upstream git@github.com:validatedpatterns-sandbox/ai-quickstart-rag.git
----

. Verify the setup of your remote repositories by running the following command:
+
[source,terminal]
----
$ git remote -v
----
+
.Example output
+
[source,terminal]
----
origin	git@github.com:your-username/ai-quickstart-rag.git (fetch)
origin	git@github.com:your-username/ai-quickstart-rag.git (push)
upstream	git@github.com:validatedpatterns-sandbox/ai-quickstart-rag.git (fetch)
upstream	git@github.com:validatedpatterns-sandbox/ai-quickstart-rag.git (push)
----

. Make a local copy of the secrets template outside of your repository to hold credentials for the pattern.
+
[WARNING]
====
Do not add, commit, or push this file to your repository. Doing so may expose personal credentials to GitHub.
====
+
Run the following command:
+
[source,terminal]
----
$ cp values-secret.yaml.template ~/values-secret-ai-quickstart-rag.yaml
----

. Populate this file with secrets, or credentials, that are needed to deploy the pattern successfully:
+
[source,terminal]
----
$ vim ~/values-secret-ai-quickstart-rag.yaml
----

.. Edit the `llm-service` section to use your HuggingFace API token:
+
[source,yaml]
----
  - name: llm-service
    fields:
    - name: hf_token
      value: hf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
----

. Optional: To customize the deployment, create and switch to a new branch by running the following command:
+
[source,terminal]
----
$ git checkout -b my-branch
----
+
Make your changes, then stage and commit them:
+
[source,terminal]
----
$ git add <changed-files>
$ git commit -m "Customize deployment"
----
+
Push the changes to your forked repository:
+
[source,terminal]
----
$ git push origin my-branch
----

[id="deploying-cluster-using-patternsh-file"]
== Deploying the pattern by using the pattern.sh file

To deploy the pattern by using the `pattern.sh` file, complete the following steps:

. Log in to your cluster by following this procedure:

.. Obtain an API token by visiting link:https://oauth-openshift.apps.<your_cluster>.<domain>/oauth/token/request[https://oauth-openshift.apps.<your_cluster>.<domain>/oauth/token/request].

.. Log in to the cluster by running the following command:
+
[source,terminal]
----
$ oc login --token=<retrieved-token> --server=https://api.<your_cluster>.<domain>:6443
----
+
Or log in by running the following command:
+
[source,terminal]
----
$ export KUBECONFIG=~/<path_to_kubeconfig>
----

. Deploy the pattern to your cluster. Run the following command:
+
[source,terminal]
----
$ ./pattern.sh make install
----

.Verification

To verify a successful installation, check the health of the ArgoCD applications:

. Run the following command:
+
[source,terminal]
----
$ ./pattern.sh make argo-healthcheck
----
+
It might take several minutes for all applications to synchronize and reach a healthy state. This includes downloading the LLM models and populating the vector database.

. Verify that the Operators are installed by navigating to *Operators -> Installed Operators* in the {ocp} web console.

. After all applications are healthy, open the RAG chatbot UI by clicking the route link in the *Networking -> Routes* page of the `ai-quickstart-rag-prod` namespace.
