---
title: Getting Started
weight: 10
aliases: /emerging-disease-detection/getting-started/
---

:toc:
:imagesdir: /images
:_content-type: ASSEMBLY

== Prerequisites

. An OpenShift cluster (Go to https://console.redhat.com/openshift/create[the OpenShift console]). Cluster must have a dynamic StorageClass to provision PersistentVolumes. See also link:../../emerging-disease-detection/cluster-sizing[sizing your cluster].
. A GitHub account (and a token for it with repositories permissions, to read from and write to your forks)

For installation tooling dependencies, see link:https://validatedpatterns.io/learn/quickstart/[Patterns quick start].

The use of this pattern depends on having a Red Hat OpenShift cluster. In this version of the validated pattern
there is no dedicated Hub / Edge cluster for the *Emerging Disease Detection* pattern. This single node pattern can be extend as a managed cluster(s) to a central hub. See link:../../emerging-disease-detection/ideas-for-customization[ideas for customization.]

If you do not have a running Red Hat OpenShift cluster you can start one on a
public or private cloud by using link:https://console.redhat.com/openshift/create[Red Hat's cloud service].

[id="utilities"]
= Utilities

A number of utilities have been built by the validated patterns team to lower the barrier to entry for using the community or Red Hat Validated Patterns. To use these utilities you will need to export some environment variables for your cloud provider:

[id="preparation"]
= Preparation

. Fork the link:https://github.com/validatedpatterns/emerging-disease-detection[emerging-disease-detection] repo on GitHub. It is necessary to fork because your fork will be updated as part of the GitOps and DevOps processes.
. Clone the forked copy of this repository.
+
[,sh]
----
git clone git@github.com:<your-username>/emerging-disease-detection.git
----

. Create a local copy of the Helm secrets values file that can safely include credentials
+
*DO NOT COMMIT THIS FILE*
+
You do not want to push credentials to GitHub.
+
[,sh]
----
cp values-secret.yaml.template ~/values-secret.yaml
vi ~/values-secret.yaml
----

*values-secret.yaml example*

[source,yaml]
----
secrets:
  - name: rhpam
    vaultPrefixes:
    - global
    fields:
    - name: rhpam_api_passwd
      value: kieserver
    - name: sso_siteadmin_password
      value: r3dh4t1!
    - name: kie_admin_password
      value: admin
    - name: kieserver_user_password
      value: kieserver
    - name: psql_passwd
      value: rhpam 

  - name: fhir-psql-db
    vaultPrefixes:
    - global
    fields:
    - name: psql_credentials_secret
      value: psql_secret
    - name: psql_user_name
      value: fhir
    - name: psql_user_passwd
      value: fhir
----

When you edit the file you can make changes to the various DB and Grafana passwords if you wish.

. Customize the `values-global.yaml` for your deployment
+
[,sh]
----
git checkout -b my-branch
vi values-global.yaml
----

*Replace instances of PROVIDE_ with your specific configuration*

[source,yaml]
----
global:
  pattern: emerging-disease-detection
  hubClusterDomain: "AUTO" # this is for test only This value is automatically fetched when Invoking against a cluster

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub
  gitOpsSpec:
    operatorChannel: gitops-1.9
----

[,sh]
----
   git add values-global.yaml
   git commit values-global.yaml
   git push origin my-branch
----

. You can deploy the pattern using the link:/infrastructure/using-validated-pattern-operator/[validated pattern operator]. If you do use the operator then skip to Validating the Environment below.
. Preview the changes that will be made to the Helm charts.
+
[,sh]
----
./pattern.sh make show
----

. Login to your cluster using oc login or exporting the KUBECONFIG
+
[,sh]
----
oc login
----
+
.or set KUBECONFIG to the path to your `kubeconfig` file. For example
+
[,sh]
----
export KUBECONFIG=~/my-ocp-env/auth/kubeconfig
----

[id="check-the-values-files-before-deployment-getting-started"]
== Check the values files before deployment

You can run a check before deployment to make sure that you have the required variables to deploy the
Emerging Disease Detection Validated Pattern.

You can run `make predeploy` to check your values. This will allow you to review your values and changed them in
the case there are typos or old values.  The values files that should be reviewed prior to deploying the
Medical Diagnosis Validated Pattern are:

|===
| Values File | Description

| values-secret.yaml / values-secret-emerging-disease-detection.yaml
| This is the values file that will include the rhpam and fhir-psql-db sections with all database et al secrets

| values-global.yaml
| File that is used to contain all the global values used by Helm
|===

= Deploy

. Apply the changes to your cluster
+
[,sh]
----
./pattern.sh make install
----
+
If the install fails and you go back over the instructions and see what was missed and change it, then run `make update` to continue the installation.

. This takes some time. Especially for the OpenShift Data Foundation operator components to install and synchronize. The `make install` provides some progress updates during the install. It can take up to twenty minutes. Compare your `make install` run progress with the following video showing a successful install.

. Check that the operators have been installed in the UI.
.. To verify, in the OpenShift Container Platform web console, navigate to *Operators → Installed Operators* page.
 .. Check that the Operator is installed in the `openshift-operators` namespace and its status is `Succeeded`.

[id="using-openshift-gitops-to-check-on-application-progress-getting-started"]
== Using OpenShift GitOps to check on Application progress

You can also check on the progress using OpenShift GitOps to check on the various applications deployed.

. Obtain the ArgoCD URLs and passwords.
+
The URLs and login credentials for ArgoCD change depending on the pattern
name and the site names they control.  Follow the instructions below to find
them, however you choose to deploy the pattern.
+
Display the fully qualified domain names, and matching login credentials, for
all ArgoCD instances:
+
[,sh]
----
ARGO_CMD=`oc get secrets -A -o jsonpath='{range .items[*]}{"oc get -n "}{.metadata.namespace}{" routes; oc -n "}{.metadata.namespace}{" extract secrets/"}{.metadata.name}{" --to=-\\n"}{end}' | grep gitops-cluster`
CMD=`echo $ARGO_CMD | sed 's|- oc|-;oc|g'`
eval $CMD
----
+
The result should look something like:
+
[,text]
----
NAME                       HOST/PORT                                                                                      PATH   SERVICES                   PORT    TERMINATION            WILDCARD
hub-gitops-server   hub-gitops-server-emerging-disease-detection-hub.apps.wh-edd-cluster.aws.validatedpatterns.com          hub-gitops-server   https   passthrough/Redirect   None
# admin.password
xsyYU6eSWtwniEk1X3jL0c2TGfQgVpDH
NAME                      HOST/PORT                                                                         PATH   SERVICES                  PORT    TERMINATION            WILDCARD
cluster                   cluster-openshift-gitops.apps.wh-edd-cluster.aws.validatedpatterns.com                          cluster                   8080    reencrypt/Allow        None
kam                       kam-openshift-gitops.apps.wh-edd-cluster.aws.validatedpatterns.com                              kam                       8443    passthrough/None       None
openshift-gitops-server   openshift-gitops-server-openshift-gitops.apps.wh-edd-cluster.aws.validatedpatterns.com          openshift-gitops-server   https   passthrough/Redirect   None
# admin.password
FdGgWHsBYkeqOczE3PuRpU1jLn7C2fD6
----
+
The most important ArgoCD instance to examine at this point is `emerging-disease-detection-hub`. This is where all the applications for the pattern can be tracked.

. Check all applications are synchronised. There are thirteen different ArgoCD "applications" deployed as part of this pattern.

[id="viewing-the-sepsis-application-dashboard-getting-started"]
== Viewing the Sepsis Detection dashboard
TO-DO: Describe how to examine the various parts of the Sepsis application

= Next Steps

link:https://groups.google.com/g/hybrid-cloud-patterns[Help & Feedback]
link:https://github.com/validatedpatterns/emerging-disease-detection/issues[Report Bugs]
