name: Lint with Vale
on: [pull_request]

jobs:
  vale:
    name: Vale linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          filter_mode: added
          vale_flags: "--no-exit --minAlertLevel=suggestion --glob=*.adoc"
          reporter: github-pr-review
          fail_on_error: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REVIEWDOG_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}